name: Deploy to Railway

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
  
      - name: Run Integration Tests
        run: ./gradlew clean test
        working-directory: ./backend

  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: backend
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
    
      # Set environment based on the branch
      - name: Set Environment Variables
        id: set_env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "RAILWAY_ENV_ID=${{ secrets.RAILWAY_PROD_ENV_ID }}" >> $GITHUB_ENV
          else
            echo "RAILWAY_ENV_ID=${{ secrets.RAILWAY_STAGING_ENV_ID }}" >> $GITHUB_ENV
          fi

      # # Deploy to the appropriate environment in the same project
      # - name: Link Railway project
      #   run: |
      #     railway link -p $RAILWAY_PROJECT_NAME -e $RAILWAY_ENV_ID -s $RAILWAY_PROJECT_NAME
      #   env:
      #     RAILWAY_PROJECT_NAME: ${{ secrets.RAILWAY_PROJECT_NAME }}
      #     RAILWAY_ENV_ID: ${{ env.RAILWAY_ENV_ID }}
      #     RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      # Deploy to the appropriate environment in the same project
      - name: Deploy to Railway
        run: RAILWAY_DEBUG=1 railway up --service=${{ env.SVC_ID }} --environment=${{ env.RAILWAY_ENV_ID }}
        working-directory: ./backend

      # Deploy to the appropriate environment in the same project
      - name: Deploy to Railway
        run: |
          unset RAILWAY_TOKEN
          railway link -p $RAILWAY_PROJECT_NAME -e $RAILWAY_ENV_ID -s $RAILWAY_PROJECT_NAME
          railway domain || true
        env:
          RAILWAY_ENV_ID: ${{ env.RAILWAY_ENV_ID }}
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_NAME: ${{ secrets.RAILWAY_PROJECT_NAME }}
        working-directory: ./backend


        #   backend-account-token="a0f7b020-1bac-4962-b053-ec41f64d43f0"
        #   backend-staging-project-token="ea8282e4-9187-49aa-90ed-2a92c5289ea4"


